Feb 11 00:00:05 debian systemd[1]: rsyslog.service: Sent signal SIGHUP to main process 1524153 (rsyslogd) on client request.
Feb 11 00:00:05 debian rsyslogd: [origin software="rsyslogd" swVersion="8.2302.0" x-pid="1524153" x-info="https://www.rsyslog.com"] rsyslogd was HUPed
Feb 11 00:00:05 debian pihole-exporter[1822867]: 2024/02/11 00:00:05 New tick of statistics: 2382 ads blocked / 55934 total DNS queries
Feb 11 00:00:05 debian systemd[1]: logrotate.service: Deactivated successfully.
Feb 11 00:00:05 debian systemd[1]: Finished logrotate.service - Rotate log files.
Feb 11 00:00:05 debian systemd[1]: logrotate.service: Consumed 3.050s CPU time.
Feb 11 00:00:06 debian python3[240728]: /root/pveexporter/lib/python3.11/site-packages/urllib3/connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'localhost'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
Feb 11 00:00:06 debian python3[240728]:   warnings.warn(
Feb 11 00:00:06 debian pvedaemon[1953904]: <root@pam> successful auth for user 'pve_exporter@pve'
Feb 11 00:00:06 debian python3[240728]: /root/pveexporter/lib/python3.11/site-packages/urllib3/connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'localhost'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
Feb 11 00:00:06 debian python3[240728]:   warnings.warn(
Feb 11 00:00:06 debian python3[240728]: /root/pveexporter/lib/python3.11/site-packages/urllib3/connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'localhost'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
Feb 11 00:00:06 debian python3[240728]:   warnings.warn(
Feb 11 00:00:06 debian python3[240728]: /root/pveexporter/lib/python3.11/site-packages/urllib3/connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'localhost'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
Feb 11 00:00:06 debian python3[240728]:   warnings.warn(
Feb 11 00:00:06 debian python3[240728]: /root/pveexporter/lib/python3.11/site-packages/urllib3/connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'localhost'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
Feb 11 00:00:06 debian python3[240728]:   warnings.warn(
Feb 11 00:00:06 debian python3[240728]: /root/pveexporter/lib/python3.11/site-packages/urllib3/connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'localhost'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
Feb 11 00:00:06 debian python3[240728]:   warnings.warn(
Feb 11 00:00:06 debian python3[240728]: /root/pveexporter/lib/python3.11/site-packages/urllib3/connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'localhost'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
Feb 11 00:00:06 debian python3[240728]:   warnings.warn(
Feb 11 00:00:06 debian python3[240728]: /root/pveexporter/lib/python3.11/site-packages/urllib3/connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'localhost'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
Feb 11 00:00:06 debian python3[240728]:   warnings.warn(
Feb 11 00:00:06 debian python3[240728]: /root/pveexporter/lib/python3.11/site-packages/urllib3/connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'localhost'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
Feb 11 00:00:06 debian python3[240728]:   warnings.warn(
Feb 11 00:00:06 debian python3[240728]: /root/pveexporter/lib/python3.11/site-packages/urllib3/connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'localhost'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
Feb 11 00:00:06 debian python3[240728]:   warnings.warn(
Feb 11 00:00:06 debian python3[240728]: /root/pveexporter/lib/python3.11/site-packages/urllib3/connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'localhost'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
Feb 11 00:00:06 debian python3[240728]:   warnings.warn(
Feb 11 00:00:06 debian python3[240728]: /root/pveexporter/lib/python3.11/site-packages/urllib3/connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'localhost'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
Feb 11 00:00:06 debian python3[240728]:   warnings.warn(
Feb 11 00:00:06 debian python3[240728]: /root/pveexporter/lib/python3.11/site-packages/urllib3/connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'localhost'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
Feb 11 00:00:06 debian python3[240728]:   warnings.warn(
Feb 11 00:00:06 debian python3[240728]: /root/pveexporter/lib/python3.11/site-packages/urllib3/connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'localhost'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
Feb 11 00:00:06 debian python3[240728]:   warnings.warn(
Feb 11 00:00:07 debian spiceproxy[662031]: worker exit
Feb 11 00:00:07 debian spiceproxy[7090]: worker 662031 finished
Feb 11 00:00:07 debian pveproxy[1952285]: worker exit
Feb 11 00:00:08 debian pveproxy[7081]: worker 1952285 finished
Feb 11 00:00:08 debian pveproxy[7081]: worker 1939385 finished
Feb 11 00:00:08 debian pveproxy[7081]: worker 1939264 finished
Feb 11 00:00:09 debian pveproxy[1956127]: worker exit
Feb 11 00:00:10 debian grafana[3610258]: logger=context userId=0 orgId=0 uname= t=2024-02-11T00:00:10.810647006+01:00 level=info msg="Request Completed" method=GET path=/ status=302 remote_addr=192.168.1.3 time_ms=0 duration=61.72Âµs size=29 referer= handler=/
Feb 11 00:00:11 debian pveproxy[1956126]: got inotify poll request in wrong process - disabling inotify
Feb 11 00:00:11 debian wssh[239963]: [I 240211 00:00:11 web:2344] 200 GET / (192.168.1.3) 0.65ms
Feb 11 00:00:11 debian pveproxy[1956126]: worker exit
Feb 11 00:00:13 debian prometheus-node-exporter[239870]: ts=2024-02-10T23:00:13.807Z caller=textfile.go:227 level=error collector=textfile msg="failed to collect textfile data" file=smartmon.prom err="failed to parse textfile data from \"/var/lib/prometheus/node-exporter/smartmon.prom\": text format parsing error in line 111: unknown metric type \"type is not sat, scsi or megaraid but nvme gauge\""
Feb 11 00:00:14 debian wssh[239963]: [I 240211 00:00:14 web:2344] 200 GET / (192.168.1.3) 0.35ms
Feb 11 00:00:15 debian pihole-exporter[1845149]: 2024/02/11 00:00:15 New tick of statistics: 10994 ads blocked / 46345 total DNS queries
Feb 11 00:00:15 debian pihole-exporter[1822867]: 2024/02/11 00:00:15 New tick of statistics: 2382 ads blocked / 55938 total DNS queries
Feb 11 00:00:16 debian python3[240728]: /root/pveexporter/lib/python3.11/site-packages/urllib3/connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'localhost'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
Feb 11 00:00:16 debian python3[240728]:   warnings.warn(
Feb 11 00:00:16 debian pvedaemon[1942700]: <root@pam> successful auth for user 'pve_exporter@pve'
Feb 11 00:00:16 debian python3[240728]: /root/pveexporter/lib/python3.11/site-packages/urllib3/connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'localhost'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
Feb 11 00:00:16 debian python3[240728]:   warnings.warn(
Feb 11 00:00:16 debian python3[240728]: /root/pveexporter/lib/python3.11/site-packages/urllib3/connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'localhost'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
Feb 11 00:00:16 debian python3[240728]:   warnings.warn(
Feb 11 00:00:16 debian python3[240728]: /root/pveexporter/lib/python3.11/site-packages/urllib3/connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'localhost'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
Feb 11 00:00:16 debian python3[240728]:   warnings.warn(
Feb 11 00:00:16 debian python3[240728]: /root/pveexporter/lib/python3.11/site-packages/urllib3/connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'localhost'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
Feb 11 00:00:16 debian python3[240728]:   warnings.warn(
Feb 11 00:00:16 debian python3[240728]: /root/pveexporter/lib/python3.11/site-packages/urllib3/connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'localhost'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
Feb 11 00:00:16 debian python3[240728]:   warnings.warn(
Feb 11 00:00:16 debian python3[240728]: /root/pveexporter/lib/python3.11/site-packages/urllib3/connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'localhost'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
Feb 11 00:00:16 debian python3[240728]:   warnings.warn(
Feb 11 00:00:16 debian python3[240728]: /root/pveexporter/lib/python3.11/site-packages/urllib3/connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'localhost'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
Feb 11 00:00:16 debian python3[240728]:   warnings.warn(
Feb 11 00:00:16 debian python3[240728]: /root/pveexporter/lib/python3.11/site-packages/urllib3/connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'localhost'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
Feb 11 00:00:16 debian python3[240728]:   warnings.warn(
Feb 11 00:00:16 debian python3[240728]: /root/pveexporter/lib/python3.11/site-packages/urllib3/connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'localhost'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
Feb 11 00:00:16 debian python3[240728]:   warnings.warn(
Feb 11 00:00:16 debian python3[240728]: /root/pveexporter/lib/python3.11/site-packages/urllib3/connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'localhost'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
Feb 11 00:00:16 debian python3[240728]:   warnings.warn(
Feb 11 00:00:16 debian python3[240728]: /root/pveexporter/lib/python3.11/site-packages/urllib3/connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'localhost'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
Feb 11 00:00:16 debian python3[240728]:   warnings.warn(
Feb 11 00:00:16 debian python3[240728]: /root/pveexporter/lib/python3.11/site-packages/urllib3/connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'localhost'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
Feb 11 00:00:16 debian python3[240728]:   warnings.warn(
Feb 11 00:00:16 debian python3[240728]: /root/pveexporter/lib/python3.11/site-packages/urllib3/connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'localhost'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
Feb 11 00:00:16 debian python3[240728]:   warnings.warn(
Feb 11 00:00:18 debian grafana[3610258]: logger=context userId=0 orgId=0 uname= t=2024-02-11T00:00:18.735069782+01:00 level=info msg="Request Completed" method=GET path=/ status=302 remote_addr=192.168.1.3 time_ms=0 duration=59.88Âµs size=29 referer= handler=/
Feb 11 00:00:20 debian grafana[3610258]: logger=context userId=0 orgId=0 uname= t=2024-02-11T00:00:20.810747837+01:00 level=info msg="Request Completed" method=GET path=/ status=302 remote_addr=192.168.1.3 time_ms=0 duration=57.49Âµs size=29 referer= handler=/
Feb 11 00:00:23 debian prometheus-node-exporter[239870]: ts=2024-02-10T23:00:23.814Z caller=textfile.go:227 level=error collector=textfile msg="failed to collect textfile data" file=smartmon.prom err="failed to parse textfile data from \"/var/lib/prometheus/node-exporter/smartmon.prom\": text format parsing error in line 111: unknown metric type \"type is not sat, scsi or megaraid but nvme gauge\""
Feb 11 00:00:24 debian wssh[239963]: [I 240211 00:00:24 web:2344] 200 GET / (192.168.1.3) 0.32ms
Feb 11 00:00:25 debian pihole-exporter[1845149]: 2024/02/11 00:00:25 New tick of statistics: 10994 ads blocked / 46351 total DNS queries
Feb 11 00:00:25 debian pihole-exporter[1822867]: 2024/02/11 00:00:25 New tick of statistics: 2382 ads blocked / 55942 total DNS queries
Feb 11 00:00:26 debian python3[240728]: /root/pveexporter/lib/python3.11/site-packages/urllib3/connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'localhost'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
Feb 11 00:00:26 debian python3[240728]:   warnings.warn(
Feb 11 00:00:26 debian pvedaemon[1942700]: <root@pam> successful auth for user 'pve_exporter@pve'
Feb 11 00:00:26 debian python3[240728]: /root/pveexporter/lib/python3.11/site-packages/urllib3/connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'localhost'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
Feb 11 00:00:26 debian python3[240728]:   warnings.warn(
Feb 11 00:00:26 debian python3[240728]: /root/pveexporter/lib/python3.11/site-packages/urllib3/connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'localhost'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
Feb 11 00:00:26 debian python3[240728]:   warnings.warn(
Feb 11 00:00:26 debian python3[240728]: /root/pveexporter/lib/python3.11/site-packages/urllib3/connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'localhost'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
Feb 11 00:00:26 debian python3[240728]:   warnings.warn(
Feb 11 00:00:26 debian python3[240728]: /root/pveexporter/lib/python3.11/site-packages/urllib3/connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'localhost'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
Feb 11 00:00:26 debian python3[240728]:   warnings.warn(
Feb 11 00:00:26 debian python3[240728]: /root/pveexporter/lib/python3.11/site-packages/urllib3/connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'localhost'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
Feb 11 00:00:26 debian python3[240728]:   warnings.warn(
Feb 11 00:00:26 debian wssh[239963]: [I 240211 00:00:26 web:2344] 200 GET / (192.168.1.3) 0.39ms
Feb 11 00:00:26 debian python3[240728]: /root/pveexporter/lib/python3.11/site-packages/urllib3/connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'localhost'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
Feb 11 00:00:26 debian python3[240728]:   warnings.warn(
Feb 11 00:00:26 debian python3[240728]: /root/pveexporter/lib/python3.11/site-packages/urllib3/connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'localhost'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
Feb 11 00:00:26 debian python3[240728]:   warnings.warn(
Feb 11 00:00:26 debian python3[240728]: /root/pveexporter/lib/python3.11/site-packages/urllib3/connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'localhost'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
Feb 11 00:00:26 debian python3[240728]:   warnings.warn(
Feb 11 00:00:26 debian python3[240728]: /root/pveexporter/lib/python3.11/site-packages/urllib3/connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'localhost'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
Feb 11 00:00:26 debian python3[240728]:   warnings.warn(
Feb 11 00:00:26 debian python3[240728]: /root/pveexporter/lib/python3.11/site-packages/urllib3/connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'localhost'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
Feb 11 00:00:26 debian python3[240728]:   warnings.warn(
Feb 11 00:00:26 debian python3[240728]: /root/pveexporter/lib/python3.11/site-packages/urllib3/connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'localhost'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
Feb 11 00:00:26 debian python3[240728]:   warnings.warn(
Feb 11 00:00:26 debian python3[240728]: /root/pveexporter/lib/python3.11/site-packages/urllib3/connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'localhost'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
Feb 11 00:00:26 debian python3[240728]:   warnings.warn(
Feb 11 00:00:26 debian python3[240728]: /root/pveexporter/lib/python3.11/site-packages/urllib3/connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'localhost'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
Feb 11 00:00:26 debian python3[240728]:   warnings.warn(
Feb 11 00:00:30 debian grafana[3610258]: logger=context userId=0 orgId=0 uname= t=2024-02-11T00:00:30.810851269+01:00 level=info msg="Request Completed" method=GET path=/ status=302 remote_addr=192.168.1.3 time_ms=0 duration=60.77Âµs size=29 referer= handler=/
Feb 11 00:00:33 debian grafana[3610258]: logger=context userId=0 orgId=0 uname= t=2024-02-11T00:00:33.733717395+01:00 level=info msg="Request Completed" method=GET path=/ status=302 remote_addr=192.168.1.3 time_ms=0 duration=69.31Âµs size=29 referer= handler=/
Feb 11 00:00:33 debian prometheus-node-exporter[239870]: ts=2024-02-10T23:00:33.807Z caller=textfile.go:227 level=error collector=textfile msg="failed to collect textfile data" file=smartmon.prom err="failed to parse textfile data from \"/var/lib/prometheus/node-exporter/smartmon.prom\": text format parsing error in line 111: unknown metric type \"type is not sat, scsi or megaraid but nvme gauge\""
Feb 11 00:00:34 debian wssh[239963]: [I 240211 00:00:34 web:2344] 200 GET / (192.168.1.3) 0.35ms
Feb 11 00:00:35 debian pihole-exporter[1845149]: 2024/02/11 00:00:35 New tick of statistics: 10994 ads blocked / 46355 total DNS queries
Feb 11 00:00:35 debian pihole-exporter[1822867]: 2024/02/11 00:00:35 New tick of statistics: 2382 ads blocked / 55946 total DNS queries
Feb 11 00:00:36 debian python3[240728]: /root/pveexporter/lib/python3.11/site-packages/urllib3/connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'localhost'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
Feb 11 00:00:36 debian python3[240728]:   warnings.warn(
Feb 11 00:00:36 debian pvedaemon[1942700]: <root@pam> successful auth for user 'pve_exporter@pve'
Feb 11 00:00:36 debian python3[240728]: /root/pveexporter/lib/python3.11/site-packages/urllib3/connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'localhost'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
Feb 11 00:00:36 debian python3[240728]:   warnings.warn(
Feb 11 00:00:36 debian python3[240728]: /root/pveexporter/lib/python3.11/site-packages/urllib3/connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'localhost'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
Feb 11 00:00:36 debian python3[240728]:   warnings.warn(
Feb 11 00:00:36 debian python3[240728]: /root/pveexporter/lib/python3.11/site-packages/urllib3/connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'localhost'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
Feb 11 00:00:36 debian python3[240728]:   warnings.warn(
Feb 11 00:00:36 debian python3[240728]: /root/pveexporter/lib/python3.11/site-packages/urllib3/connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'localhost'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
Feb 11 00:00:36 debian python3[240728]:   warnings.warn(
Feb 11 00:00:36 debian python3[240728]: /root/pveexporter/lib/python3.11/site-packages/urllib3/connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'localhost'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
Feb 11 00:00:36 debian python3[240728]:   warnings.warn(
Feb 11 00:00:36 debian python3[240728]: /root/pveexporter/lib/python3.11/site-packages/urllib3/connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'localhost'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
Feb 11 00:00:36 debian python3[240728]:   warnings.warn(
Feb 11 00:00:36 debian python3[240728]: /root/pveexporter/lib/python3.11/site-packages/urllib3/connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'localhost'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
Feb 11 00:00:36 debian python3[240728]:   warnings.warn(
Feb 11 00:00:36 debian python3[240728]: /root/pveexporter/lib/python3.11/site-packages/urllib3/connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'localhost'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
Feb 11 00:00:36 debian python3[240728]:   warnings.warn(
Feb 11 00:00:36 debian python3[240728]: /root/pveexporter/lib/python3.11/site-packages/urllib3/connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'localhost'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
Feb 11 00:00:36 debian python3[240728]:   warnings.warn(
Feb 11 00:00:36 debian python3[240728]: /root/pveexporter/lib/python3.11/site-packages/urllib3/connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'localhost'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
Feb 11 00:00:36 debian python3[240728]:   warnings.warn(
Feb 11 00:00:36 debian python3[240728]: /root/pveexporter/lib/python3.11/site-packages/urllib3/connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'localhost'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
Feb 11 00:00:36 debian python3[240728]:   warnings.warn(
Feb 11 00:00:36 debian python3[240728]: /root/pveexporter/lib/python3.11/site-packages/urllib3/connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'localhost'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
Feb 11 00:00:36 debian python3[240728]:   warnings.warn(
Feb 11 00:00:36 debian python3[240728]: /root/pveexporter/lib/python3.11/site-packages/urllib3/connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'localhost'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
Feb 11 00:00:36 debian python3[240728]:   warnings.warn(
Feb 11 00:00:40 debian grafana[3610258]: logger=context userId=0 orgId=0 uname= t=2024-02-11T00:00:40.811334733+01:00 level=info msg="Request Completed" method=GET path=/ status=302 remote_addr=192.168.1.3 time_ms=0 duration=62.5Âµs size=29 referer= handler=/
Feb 11 00:00:41 debian wssh[239963]: [I 240211 00:00:41 web:2344] 200 GET / (192.168.1.3) 0.36ms
Feb 11 00:00:43 debian prometheus-node-exporter[239870]: ts=2024-02-10T23:00:43.803Z caller=textfile.go:227 level=error collector=textfile msg="failed to collect textfile data" file=smartmon.prom err="failed to parse textfile data from \"/var/lib/prometheus/node-exporter/smartmon.prom\": text format parsing error in line 111: unknown metric type \"type is not sat, scsi or megaraid but nvme gauge\""
Feb 11 00:00:44 debian wssh[239963]: [I 240211 00:00:44 web:2344] 200 GET / (192.168.1.3) 0.35ms
Feb 11 00:00:45 debian pihole-exporter[1845149]: 2024/02/11 00:00:45 New tick of statistics: 10994 ads blocked / 46355 total DNS queries
Feb 11 00:00:45 debian pihole-exporter[1822867]: 2024/02/11 00:00:45 New tick of statistics: 2382 ads blocked / 55950 total DNS queries
Feb 11 00:00:46 debian python3[240728]: /root/pveexporter/lib/python3.11/site-packages/urllib3/connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'localhost'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
Feb 11 00:00:46 debian python3[240728]:   warnings.warn(
Feb 11 00:00:46 debian pvedaemon[1942700]: <root@pam> successful auth for user 'pve_exporter@pve'
Feb 11 00:00:46 debian python3[240728]: /root/pveexporter/lib/python3.11/site-packages/urllib3/connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'localhost'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
Feb 11 00:00:46 debian python3[240728]:   warnings.warn(
Feb 11 00:00:46 debian python3[240728]: /root/pveexporter/lib/python3.11/site-packages/urllib3/connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'localhost'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
Feb 11 00:00:46 debian python3[240728]:   warnings.warn(
Feb 11 00:00:46 debian python3[240728]: /root/pveexporter/lib/python3.11/site-packages/urllib3/connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'localhost'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
Feb 11 00:00:46 debian python3[240728]:   warnings.warn(
Feb 11 00:00:46 debian python3[240728]: /root/pveexporter/lib/python3.11/site-packages/urllib3/connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'localhost'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
Feb 11 00:00:46 debian python3[240728]:   warnings.warn(
Feb 11 00:00:46 debian python3[240728]: /root/pveexporter/lib/python3.11/site-packages/urllib3/connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'localhost'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
Feb 11 00:00:46 debian python3[240728]:   warnings.warn(
Feb 11 00:00:46 debian python3[240728]: /root/pveexporter/lib/python3.11/site-packages/urllib3/connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'localhost'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
Feb 11 00:00:46 debian python3[240728]:   warnings.warn(
Feb 11 00:00:46 debian python3[240728]: /root/pveexporter/lib/python3.11/site-packages/urllib3/connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'localhost'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
Feb 11 00:00:46 debian python3[240728]:   warnings.warn(
Feb 11 00:00:46 debian python3[240728]: /root/pveexporter/lib/python3.11/site-packages/urllib3/connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'localhost'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
Feb 11 00:00:46 debian python3[240728]:   warnings.warn(
Feb 11 00:00:46 debian python3[240728]: /root/pveexporter/lib/python3.11/site-packages/urllib3/connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'localhost'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
Feb 11 00:00:46 debian python3[240728]:   warnings.warn(
Feb 11 00:00:46 debian python3[240728]: /root/pveexporter/lib/python3.11/site-packages/urllib3/connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'localhost'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
Feb 11 00:00:46 debian python3[240728]:   warnings.warn(
Feb 11 00:00:46 debian python3[240728]: /root/pveexporter/lib/python3.11/site-packages/urllib3/connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'localhost'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
Feb 11 00:00:46 debian python3[240728]:   warnings.warn(
Feb 11 00:00:46 debian python3[240728]: /root/pveexporter/lib/python3.11/site-packages/urllib3/connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'localhost'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
Feb 11 00:00:46 debian python3[240728]:   warnings.warn(
Feb 11 00:00:46 debian python3[240728]: /root/pveexporter/lib/python3.11/site-packages/urllib3/connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'localhost'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
Feb 11 00:00:46 debian python3[240728]:   warnings.warn(
Feb 11 00:00:48 debian grafana[3610258]: logger=context userId=0 orgId=0 uname= t=2024-02-11T00:00:48.733499642+01:00 level=info msg="Request Completed" method=GET path=/ status=302 remote_addr=192.168.1.3 time_ms=0 duration=58.37Âµs size=29 referer= handler=/
Feb 11 00:00:50 debian grafana[3610258]: logger=context userId=0 orgId=0 uname= t=2024-02-11T00:00:50.811535133+01:00 level=info msg="Request Completed" method=GET path=/ status=302 remote_addr=192.168.1.3 time_ms=0 duration=68.1Âµs size=29 referer= handler=/
Feb 11 00:00:53 debian prometheus-node-exporter[239870]: ts=2024-02-10T23:00:53.815Z caller=textfile.go:227 level=error collector=textfile msg="failed to collect textfile data" file=smartmon.prom err="failed to parse textfile data from \"/var/lib/prometheus/node-exporter/smartmon.prom\": text format parsing error in line 111: unknown metric type \"type is not sat, scsi or megaraid but nvme gauge\""
Feb 11 00:00:54 debian wssh[239963]: [I 240211 00:00:54 web:2344] 200 GET / (192.168.1.3) 0.36ms
Feb 11 00:00:55 debian pihole-exporter[1845149]: 2024/02/11 00:00:55 New tick of statistics: 10994 ads blocked / 46359 total DNS queries
Feb 11 00:00:55 debian pihole-exporter[1822867]: 2024/02/11 00:00:55 New tick of statistics: 2382 ads blocked / 55956 total DNS queries
Feb 11 00:00:56 debian python3[240728]: /root/pveexporter/lib/python3.11/site-packages/urllib3/connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'localhost'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
Feb 11 00:00:56 debian python3[240728]:   warnings.warn(
Feb 11 00:00:56 debian pvedaemon[1953904]: <root@pam> successful auth for user 'pve_exporter@pve'
Feb 11 00:00:56 debian python3[240728]: /root/pveexporter/lib/python3.11/site-packages/urllib3/connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'localhost'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
Feb 11 00:00:56 debian python3[240728]:   warnings.warn(
Feb 11 00:00:56 debian python3[240728]: /root/pveexporter/lib/python3.11/site-packages/urllib3/connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'localhost'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
Feb 11 00:00:56 debian python3[240728]:   warnings.warn(
Feb 11 00:00:56 debian python3[240728]: /root/pveexporter/lib/python3.11/site-packages/urllib3/connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'localhost'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
Feb 11 00:00:56 debian python3[240728]:   warnings.warn(
Feb 11 00:00:56 debian python3[240728]: /root/pveexporter/lib/python3.11/site-packages/urllib3/connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'localhost'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
Feb 11 00:00:56 debian python3[240728]:   warnings.warn(
Feb 11 00:00:56 debian python3[240728]: /root/pveexporter/lib/python3.11/site-packages/urllib3/connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'localhost'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
Feb 11 00:00:56 debian python3[240728]:   warnings.warn(
Feb 11 00:00:56 debian python3[240728]: /root/pveexporter/lib/python3.11/site-packages/urllib3/connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'localhost'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
Feb 11 00:00:56 debian python3[240728]:   warnings.warn(
Feb 11 00:00:56 debian python3[240728]: /root/pveexporter/lib/python3.11/site-packages/urllib3/connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'localhost'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
Feb 11 00:00:56 debian python3[240728]:   warnings.warn(
Feb 11 00:00:56 debian python3[240728]: /root/pveexporter/lib/python3.11/site-packages/urllib3/connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'localhost'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
Feb 11 00:00:56 debian python3[240728]:   warnings.warn(
Feb 11 00:00:56 debian python3[240728]: /root/pveexporter/lib/python3.11/site-packages/urllib3/connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'localhost'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
Feb 11 00:00:56 debian python3[240728]:   warnings.warn(
Feb 11 00:00:56 debian wssh[239963]: [I 240211 00:00:56 web:2344] 200 GET / (192.168.1.3) 0.29ms
Feb 11 00:00:56 debian python3[240728]: /root/pveexporter/lib/python3.11/site-packages/urllib3/connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'localhost'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
Feb 11 00:00:56 debian python3[240728]:   warnings.warn(
Feb 11 00:00:56 debian python3[240728]: /root/pveexporter/lib/python3.11/site-packages/urllib3/connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'localhost'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
Feb 11 00:00:56 debian python3[240728]:   warnings.warn(
Feb 11 00:00:56 debian python3[240728]: /root/pveexporter/lib/python3.11/site-packages/urllib3/connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'localhost'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
Feb 11 00:00:56 debian python3[240728]:   warnings.warn(
Feb 11 00:00:56 debian python3[240728]: /root/pveexporter/lib/python3.11/site-packages/urllib3/connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'localhost'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
Feb 11 00:00:56 debian python3[240728]:   warnings.warn(
Feb 11 00:01:00 debian grafana[3610258]: logger=context userId=0 orgId=0 uname= t=2024-02-11T00:01:00.811255906+01:00 level=info msg="Request Completed" method=GET path=/ status=302 remote_addr=192.168.1.3 time_ms=0 duration=62.51Âµs size=29 referer= handler=/
Feb 11 00:01:03 debian grafana[3610258]: logger=context userId=0 orgId=0 uname= t=2024-02-11T00:01:03.734325691+01:00 level=info msg="Request Completed" method=GET path=/ status=302 remote_addr=192.168.1.3 time_ms=0 duration=67.7Âµs size=29 referer= handler=/
Feb 11 00:01:03 debian prometheus-node-exporter[239870]: ts=2024-02-10T23:01:03.803Z caller=textfile.go:227 level=error collector=textfile msg="failed to collect textfile data" file=smartmon.prom err="failed to parse textfile data from \"/var/lib/prometheus/node-exporter/smartmon.prom\": text format parsing error in line 111: unknown metric type \"type is not sat, scsi or megaraid but nvme gauge\""
Feb 11 00:01:04 debian wssh[239963]: [I 240211 00:01:04 web:2344] 200 GET / (192.168.1.3) 0.37ms
Feb 11 00:01:05 debian pihole-exporter[1845149]: 2024/02/11 00:01:05 New tick of statistics: 10994 ads blocked / 46359 total DNS queries
Feb 11 00:01:05 debian pihole-exporter[1822867]: 2024/02/11 00:01:05 New tick of statistics: 2382 ads blocked / 55960 total DNS queries
Feb 11 00:01:06 debian python3[240728]: /root/pveexporter/lib/python3.11/site-packages/urllib3/connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'localhost'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
Feb 11 00:01:06 debian python3[240728]:   warnings.warn(
Feb 11 00:01:06 debian pvedaemon[1939128]: <root@pam> successful auth for user 'pve_exporter@pve'
Feb 11 00:01:06 debian python3[240728]: /root/pveexporter/lib/python3.11/site-packages/urllib3/connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'localhost'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
Feb 11 00:01:06 debian python3[240728]:   warnings.warn(
Feb 11 00:01:06 debian python3[240728]: /root/pveexporter/lib/python3.11/site-packages/urllib3/connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'localhost'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
Feb 11 00:01:06 debian python3[240728]:   warnings.warn(
Feb 11 00:01:06 debian python3[240728]: /root/pveexporter/lib/python3.11/site-packages/urllib3/connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'localhost'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
Feb 11 00:01:06 debian python3[240728]:   warnings.warn(
Feb 11 00:01:06 debian python3[240728]: /root/pveexporter/lib/python3.11/site-packages/urllib3/connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'localhost'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
Feb 11 00:01:06 debian python3[240728]:   warnings.warn(
Feb 11 00:01:06 debian python3[240728]: /root/pveexporter/lib/python3.11/site-packages/urllib3/connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'localhost'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
Feb 11 00:01:06 debian python3[240728]:   warnings.warn(
Feb 11 00:01:06 debian python3[240728]: /root/pveexporter/lib/python3.11/site-packages/urllib3/connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'localhost'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
Feb 11 00:01:06 debian python3[240728]:   warnings.warn(
Feb 11 00:01:06 debian python3[240728]: /root/pveexporter/lib/python3.11/site-packages/urllib3/connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'localhost'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
Feb 11 00:01:06 debian python3[240728]:   warnings.warn(
Feb 11 00:01:06 debian python3[240728]: /root/pveexporter/lib/python3.11/site-packages/urllib3/connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'localhost'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
Feb 11 00:01:06 debian python3[240728]:   warnings.warn(
Feb 11 00:01:06 debian python3[240728]: /root/pveexporter/lib/python3.11/site-packages/urllib3/connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'localhost'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
Feb 11 00:01:06 debian python3[240728]:   warnings.warn(
Feb 11 00:01:06 debian python3[240728]: /root/pveexporter/lib/python3.11/site-packages/urllib3/connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'localhost'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
Feb 11 00:01:06 debian python3[240728]:   warnings.warn(
Feb 11 00:01:06 debian python3[240728]: /root/pveexporter/lib/python3.11/site-packages/urllib3/connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'localhost'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
Feb 11 00:01:06 debian python3[240728]:   warnings.warn(
Feb 11 00:01:06 debian python3[240728]: /root/pveexporter/lib/python3.11/site-packages/urllib3/connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'localhost'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
Feb 11 00:01:06 debian python3[240728]:   warnings.warn(
Feb 11 00:01:06 debian python3[240728]: /root/pveexporter/lib/python3.11/site-packages/urllib3/connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'localhost'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
Feb 11 00:01:06 debian python3[240728]:   warnings.warn(
Feb 11 00:01:10 debian grafana[3610258]: logger=context userId=0 orgId=0 uname= t=2024-02-11T00:01:10.810922284+01:00 level=info msg="Request Completed" method=GET path=/ status=302 remote_addr=192.168.1.3 time_ms=0 duration=62.949Âµs size=29 referer= handler=/
Feb 11 00:01:11 debian wssh[239963]: [I 240211 00:01:11 web:2344] 200 GET / (192.168.1.3) 0.38ms
Feb 11 00:01:13 debian prometheus-node-exporter[239870]: ts=2024-02-10T23:01:13.807Z caller=textfile.go:227 level=error collector=textfile msg="failed to collect textfile data" file=smartmon.prom err="failed to parse textfile data from \"/var/lib/prometheus/node-exporter/smartmon.prom\": text format parsing error in line 111: unknown metric type \"type is not sat, scsi or megaraid but nvme gauge\""
Feb 11 00:01:14 debian wssh[239963]: [I 240211 00:01:14 web:2344] 200 GET / (192.168.1.3) 0.35ms
Feb 11 00:01:15 debian pihole-exporter[1845149]: 2024/02/11 00:01:15 New tick of statistics: 10994 ads blocked / 46359 total DNS queries
Feb 11 00:01:15 debian pihole-exporter[1822867]: 2024/02/11 00:01:15 New tick of statistics: 2382 ads blocked / 55964 total DNS queries
Feb 11 00:01:16 debian python3[240728]: /root/pveexporter/lib/python3.11/site-packages/urllib3/connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'localhost'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
Feb 11 00:01:16 debian python3[240728]:   warnings.warn(
Feb 11 00:01:16 debian pvedaemon[1953904]: <root@pam> successful auth for user 'pve_exporter@pve'
Feb 11 00:01:16 debian python3[240728]: /root/pveexporter/lib/python3.11/site-packages/urllib3/connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'localhost'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
Feb 11 00:01:16 debian python3[240728]:   warnings.warn(
Feb 11 00:01:16 debian python3[240728]: /root/pveexporter/lib/python3.11/site-packages/urllib3/connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'localhost'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
Feb 11 00:01:16 debian python3[240728]:   warnings.warn(
Feb 11 00:01:16 debian python3[240728]: /root/pveexporter/lib/python3.11/site-packages/urllib3/connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'localhost'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
Feb 11 00:01:16 debian python3[240728]:   warnings.warn(
Feb 11 00:01:16 debian python3[240728]: /root/pveexporter/lib/python3.11/site-packages/urllib3/connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'localhost'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
Feb 11 00:01:16 debian python3[240728]:   warnings.warn(
Feb 11 00:01:16 debian python3[240728]: /root/pveexporter/lib/python3.11/site-packages/urllib3/connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'localhost'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
Feb 11 00:01:16 debian python3[240728]:   warnings.warn(
Feb 11 00:01:16 debian python3[240728]: /root/pveexporter/lib/python3.11/site-packages/urllib3/connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'localhost'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
Feb 11 00:01:16 debian python3[240728]:   warnings.warn(
Feb 11 00:01:16 debian python3[240728]: /root/pveexporter/lib/python3.11/site-packages/urllib3/connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'localhost'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
Feb 11 00:01:16 debian python3[240728]:   warnings.warn(
Feb 11 00:01:16 debian python3[240728]: /root/pveexporter/lib/python3.11/site-packages/urllib3/connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'localhost'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
Feb 11 00:01:16 debian python3[240728]:   warnings.warn(
Feb 11 00:01:16 debian python3[240728]: /root/pveexporter/lib/python3.11/site-packages/urllib3/connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'localhost'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
Feb 11 00:01:16 debian python3[240728]:   warnings.warn(
Feb 11 00:01:16 debian python3[240728]: /root/pveexporter/lib/python3.11/site-packages/urllib3/connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'localhost'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
Feb 11 00:01:16 debian python3[240728]:   warnings.warn(
Feb 11 00:01:16 debian python3[240728]: /root/pveexporter/lib/python3.11/site-packages/urllib3/connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'localhost'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
Feb 11 00:01:16 debian python3[240728]:   warnings.warn(
Feb 11 00:01:16 debian python3[240728]: /root/pveexporter/lib/python3.11/site-packages/urllib3/connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'localhost'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
Feb 11 00:01:16 debian python3[240728]:   warnings.warn(
Feb 11 00:01:16 debian python3[240728]: /root/pveexporter/lib/python3.11/site-packages/urllib3/connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'localhost'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
Feb 11 00:01:16 debian python3[240728]:   warnings.warn(
Feb 11 00:01:18 debian grafana[3610258]: logger=context userId=0 orgId=0 uname= t=2024-02-11T00:01:18.733665889+01:00 level=info msg="Request Completed" method=GET path=/ status=302 remote_addr=192.168.1.3 time_ms=0 duration=59.059Âµs size=29 referer= handler=/
Feb 11 00:01:20 debian grafana[3610258]: logger=context userId=0 orgId=0 uname= t=2024-02-11T00:01:20.810500302+01:00 level=info msg="Request Completed" method=GET path=/ status=302 remote_addr=192.168.1.3 time_ms=0 duration=56.26Âµs size=29 referer= handler=/
Feb 11 00:01:23 debian prometheus-node-exporter[239870]: ts=2024-02-10T23:01:23.816Z caller=textfile.go:227 level=error collector=textfile msg="failed to collect textfile data" file=smartmon.prom err="failed to parse textfile data from \"/var/lib/prometheus/node-exporter/smartmon.prom\": text format parsing error in line 111: unknown metric type \"type is not sat, scsi or megaraid but nvme gauge\""
Feb 11 00:01:24 debian wssh[239963]: [I 240211 00:01:24 web:2344] 200 GET / (192.168.1.3) 0.36ms
Feb 11 00:01:25 debian pihole-exporter[1845149]: 2024/02/11 00:01:25 New tick of statistics: 10994 ads blocked / 46362 total DNS queries
Feb 11 00:01:25 debian pihole-exporter[1822867]: 2024/02/11 00:01:25 New tick of statistics: 2382 ads blocked / 55968 total DNS queries
Feb 11 00:01:26 debian python3[240728]: /root/pveexporter/lib/python3.11/site-packages/urllib3/connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'localhost'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
Feb 11 00:01:26 debian python3[240728]:   warnings.warn(
Feb 18 00:00:08 debian spiceproxy[7090]: worker 1276521 finished
